server:
  port: 9002

spring:
  application:
    name: USER-SERVICE

auth:
  url: http://localhost:9004

eureka:
  client:
    reister-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost