server:
  port: 9003

spring:
  application:
    name: OFFICE-SERVICE

client:
  secret: secret
  id: 1

adapter:
  url: http://localhost:9002/user/

eureka:
  client:
    reister-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost